version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelexpense
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/travelexpense?schema=public
      CORS_ORIGIN: '*'
    depends_on:
      - db
    ports:
      - '4000:4000'
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:4000/health"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 15s
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost:4000
    ports:
      - '3000:3000'
    depends_on:
      backend:
        condition: service_healthy
volumes:
  pgdata: {}
